Fix:fontStyles and add default Image
canopas/canopas-blog pull request #48
Opened 2023-03-24 11:09 UTC by cp-mansi-d

2023-03-24 11:39 UTC, cp-priyanka-g approved these changes

2023-03-24 11:40 UTC, cp-jagruti-a approved these changes

2023-03-27 05:22 UTC, cp-sumi-k requested changes

2023-03-27 08:36 UTC, cp-sumi-k approved these changes

2023-03-27 08:36 UTC, cp-sumi-k commented on utils.js
> +    : "https://www.aprompt.co.uk/uploads/blog/bloggers-wiltshire.jpg";
Let's use `https://canopas.com/apple-touch-icon.png`

2023-03-27 10:25 UTC, cp-sumi-k approved these changes

2023-03-27 10:25 UTC, merged