Get blog by category
canopas/canopas-blog pull request #7
Opened 2022-11-22 08:23 UTC by cp-priyanka-g

2022-11-22 11:16 UTC, cp-shruti-s commented on config.js
> +  STRAPI_URL: "http://localhost:1337",
Remove the local URL

2022-11-22 11:18 UTC, cp-shruti-s commented on lib/post.js
> +export { fetchPost, getReadingTime, formateDate,fetchCategory};
Merge with master

2022-11-22 11:18 UTC, cp-shruti-s commented on pages/categories/[slug].js
> +  console.log(category)
remove console log

2022-11-22 11:20 UTC, cp-shruti-s commented on pages/categories/[slug].js
> +  for (let i = 0; i < category.data.length; i++) {
If is it not necessary then remove

2022-11-22 11:20 UTC, cp-shruti-s commented on pages/categories/[slug].js
> +                          <span>{post.readingTime}</span>
How to calculate post reading time ??

2022-11-22 11:22 UTC, cp-shruti-s commented on pages/index.js
> +    props: { posts},
please configure prettier for the code format

2022-11-22 12:54 UTC, cp-shruti-s commented on lib/post.js
> +export { fetchPost, getReadingTime, formateDate, fetchAuthor,fetchCategory};
Where is the category api configuration method ??

2022-11-24 08:40 UTC, cp-sumi-k commented on lib/post.js
> +    ? `${STRAPI_URL}/api/posts/${slug}?populate=*`
Make sure that other code should not be changed. `*` was `deep`

2022-11-24 08:43 UTC, cp-sumi-k requested changes

2022-11-24 08:43 UTC, cp-sumi-k commented on lib/post.js
> +    ? `${STRAPI_URL}/api/categories/${slug}?populate=*`
`*` can be `deep` to get full response

2022-11-24 08:43 UTC, cp-sumi-k commented on pages/categories/[slug].js
> +  const Posts = await fetchCategory();
Give relative name to const

2022-11-29 09:04 UTC, cp-sumi-k requested changes

2022-11-29 09:09 UTC, cp-shruti-s commented
![Screenshot from 2022-11-29 14-38-03](https://user-images.githubusercontent.com/94360312/204486656-499fa747-ac10-471c-880a-e20076663b9b.png)

Refer the more blog website because tags ui is not suitable

2022-11-29 09:13 UTC, cp-shruti-s commented on pages/categories/[slug].js
> +          Blog By Category
Header should be common in website

2022-11-30 10:35 UTC, cp-shruti-s commented on pages/index.js
> +        var tag = post.tags.data[i].attributes;
this variable is used anywhere ??

2022-11-30 10:56 UTC, cp-shruti-s approved these changes

2022-12-02 07:37 UTC, cp-sumi-k approved these changes

2022-12-05 05:10 UTC, merged